# Generated by Django 6.1 on 2026-09-22 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_2fa_enabled_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin/CEO'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('STAFF', 'General Staff'), ('INTERN', 'Intern')], default='STAFF', max_length=20),
        ),
    ]
