# Generated by Django 6.1 on 2026-09-08 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LEAD_ASSIGNED', 'New Lead Assignment'), ('TASK_ASSIGNED', 'New Task Assignment'), ('TASK_DUE_SOON', 'Upcoming Task Deadline'), ('TASK_OVERDUE', 'Overdue Task'), ('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_OVERDUE', 'Overdue Payment'), ('RENEWAL_DUE', 'Upcoming Renewal'), ('PROJECT_UPDATE', 'Project Update')], max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
