# Generated by Django 6.1 on 2026-09-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAD_ASSIGNED', 'New Lead Assignment'), ('TASK_ASSIGNED', 'New Task Assignment'), ('TASK_DUE_SOON', 'Upcoming Task Deadline'), ('TASK_OVERDUE', 'Overdue Task'), ('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_OVERDUE', 'Overdue Payment'), ('RENEWAL_DUE', 'Upcoming Renewal'), ('PROJECT_UPDATE', 'Project Update'), ('TASK_STATUS_CHANGED', 'Task Status Update')], max_length=30),
        ),
    ]
