# Generated by Django 6.1 on 2026-08-25 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('service_interested_in', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_source', models.CharField(choices=[('FACEBOOK_ADS', 'Facebook Ads'), ('INSTAGRAM_ADS', 'Instagram Ads'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('WALK_IN', 'Walk-in'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
